name: CI Pipeline

on:
  push:
    branches: [ "dev", "staging", "main" ]
  pull_request:
    branches: [ "dev", "staging", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Java (Temurin) - version 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      # 3. Build and Test with Maven
      - name: Build with Maven
        run: mvn clean install

      # 4. (Optional) Upload test results or coverage reports
      #    You can later add steps here for coverage analysis (e.g., JaCoCo).
