name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 17 using Temurin distribution; Maven dependencies are cached automatically
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3. Build the project using Maven (this will compile and package your app)
      - name: Build with Maven
        run: mvn clean install

      # 4. Run the tests to ensure nothing is broken
      - name: Run Tests
        run: mvn test

      # 5. Archive the built JAR file as an artifact for later steps or downloads
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: target/*.jar
